name: Calculation

# Trigger on push and pull requests to the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 21 and enable Maven cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Đảm bảo khớp với version trong pom.xml
          distribution: 'temurin'
          cache: maven

      # Build (run tests and package)
      - name: Build with Maven (Test and Package)
        run: mvn -B clean package

      # Upload built JAR artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculation-app-jar
          path: target/*.jar